spring.application.name=leastcount
spring.mvc.servlet.load-on-startup=1
logging.level.root=INFO
logging.file.name=leastcount.log
redis.server.host=127.0.0.1
redis.server.port=6379
spring.datasource.url=jdbc:mysql://sql12.freesqldatabase.com:3306/sql12773924
spring.datasource.username=sql12773924
spring.datasource.password=78PWXaSKL8
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
